---
- hosts: L00-SW01
  connection: local
  tasks:
    - aruba_command:
        commands:
          - display interface brief
#        wait_for:
#          - result[0] contains A1
#        register: out
#    - debug: var=out.stdout_lines
