---
- hosts: hpe
  gather_facts: true
  connection: local
  name: HPE backup playbook

  tasks:
    - name: Test directory
      file:
        path: "{{ backup_location }}"
        state: directory
        owner: root
        group: root
        mode: 0700
    - name: Retreive config
      command: sshpass -p "{{ ansible_password }}" sftp -q "{{ ansible_user }}"@"{{ ansible_ssh_host }}":startup.cfg "{{ backup_location }}"/"{{inventory_hostname}}"-"{{ ansible_ssh_host }}".conf
      ignore_errors: yes