---
- name: Install Firefox certificates
  hosts: windows
  tasks:
    - name: Certyfikaty z Windows
      win_copy:
         src: /home/mjarosz/ff_cert/Enableroot.js
         dest: C:\Program Files\Mozilla Firefox\Defaults\Pref\
    - name: Dodanie certyfikatów
      win_copy:
         src: /home/mjarosz/ff_cert/
         dest: c:\Windows\Temp\ff_cert

    - name: Run script
      win_command: c:\Windows\Temp\ff_cert\ImportCAtoFirefox.bat
